server:
  port: 8084
  
spring:
  application:
    name: ApiGateway
    
#  main:
#    allow-bean-definition-overriding: true
    
  cloud:
    gateway:
      mvc:
        routes:
        - id: USERSERVICE
          uri:
            lb://USERSERVICE
          predicates:
          - path=/api/user/**
          
        - id: HOTELSERVICE
          uri:
            lb://HOTELSERVICE
          predicates:
          - path=/hotels/**,/staffs/**
          
        - id: RATINGSERVICE
          uri:
            lb://RATINGSERVICE
          predicates:
          - path=/ratings/**
          
okta:
  oauth2:
    issuer: https://dev-59401106.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaj836zz44PgTa8m5d7
    client-secret: 5mWKL6FvCARQuWBbl2JWuEtXqTMWZjdbOoZlg5OWYU6Z49HFyp8nyQk0UFD_jd3M
    scopes: openid, profile, email, offline_access

