server:
  port: 8084
  
spring:
  application:
    name: ApiGateway
    
  cloud:
    gateway:
      mvc:
        routes:
        - id: USERSERVICE
          uri:
            lb://USERSERVICE
          predicates:
          - path=/api/user/**
          
        - id: HOTELSERVICE
          uri:
            lb://HOTELSERVICE
          predicates:
          - path=/hotels/**,/staffs/**
          
        - id: RATINGSERVICE
          uri:
            lb://RATINGSERVICE
          predicates:
          - path=/ratings/**
                  
    
    
eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
